# Generated by Django 6.0.6 on 2026-07-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='valor',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
    ]
