# Generated by Django 6.0.6 on 2026-07-05 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_alter_resposta_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='pergunta_mae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependentes', to='checklist.pergunta'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='peso',
            field=models.FloatField(default=1.0),
        ),
    ]
